---
title: "RoadAccidentSeverity"
author: "Alexandre Robin"
date: "`r Sys.Date()`"
output: rmdformats::material
---

```{r setup, echo=False, include=FALSE}

require(dplyr, install.packages('dplyr'))
require(knitr, install.packages('knitr'))
require(ggplot2, install.packages('ggplot'))
require(naniar, install.packages('naniar'))
require(rmdformats, install.packages('rmdformats'))
require(tidyr, install.packages('tidyr'))
require(visdat, install.packages('visdat'))

knitr::opts_chunk$set(echo = TRUE)
```

# Exploratory Data Analysis

```{r cars}
caract <- read.csv2('../data/carcteristiques-2021.csv', 
                    header=TRUE,
                    sep=';')

lieux <- read.csv2('../data/lieux-2021.csv',
                    header=TRUE, 
                    sep=";")



```

```{r}
set_numericals <- function(data, list_var){
  require(dplyr, install.packages('dplyr'))
  list_var <- unlist(list_var)
  data <- data %>% mutate_at(vars(matches(list_var)), as.integer)
  return(data)
}

set_factors <- function(data, list_var){
  require(dplyr, install.packages('dplyr'))
  list_var <- unlist(list_var)
  data <- data %>% mutate_at(vars(matches(list_var)), as.factor)
  return(data)
}

set_strings <- function(data, list_var){
  require(dplyr, install.packages('dplyr'))
  list_var <- unlist(list_var)
  data <- data %>% mutate_at(vars(matches(list_var)), as.character)
  return(data)
}

set_data <- function(data, var_numericals, var_factors, var_strings){
  if(length(var_numericals)!=0)
    data <- set_numericals(data, var_numericals)
  if(length(var_factors)!=0)
    data <- set_factors(data, var_factors)
  if(length(var_strings)!=0)
    data <- set_strings(data, var_strings)
  return(data)
}

del_vars <- function(data, vars){
  vars <- unlist(vars)
  for(var in vars) {
    data <-  data[, -which(names(data) == var)]
  }
  return(data)
}

get_missing <- function(df){ 
  variables <- names(df) 
  dtypes <- sapply(df, class)
  count <- sapply(df, length) 
  unique <- sapply(df, function(x) length(unique(na.omit(x)))) 
  missing <- sapply(df, function(x) sum(is.na(x))) 
  missing_prop <- round(missing/count*100, 2) 
  output <- data.frame(variable=variables, 
                       dtype=dtypes, 
                       count=count, 
                       unique=unique, 
                       missing=missing, 
                       missing_prop=missing_prop) 
  return(output) 
}


boxplot <- function(data, target, var){
  ggplot(data, aes(y=data[,target], x=data[,var],colour=data[,var],fill=data[,var]))+
  geom_boxplot(alpha=0.5, outlier.alpha=0)+geom_jitter(width=0.25)+
  stat_summary(fun=mean, colour="black", geom="point",shape=18, size=2)+
  scale_color_discrete(name=var) + scale_fill_discrete(name=var)+
  labs(x=var, y=target, title = paste(target, "vs", var))
}

plot_multi_var <- function(train, target, var_quant, var_qual){
  ggplot(train, aes_string(x = var_quant, y =target, color=var_qual)) +
  geom_point()+geom_smooth(method = "lm")
}
```


## Caractéristiques

```{r}
caract <- read.csv2('../data/carcteristiques-2021.csv', 
                    header=TRUE,
                    sep=';')
```


```{r}
caract %>% head
caract %>% str
caract %>% summary
```

```{r}
caract[caract=="N/A"] <-  NA
caract %>% mutate(across(-c(long,lat), ~ifelse(.==-1, NA, .)))
```

```{r}
caract %>% gg_miss_var()
caract %>% vis_dat(warn_large_data=FALSE)
caract %>% vis_miss(warn_large_data=FALSE)
caract %>% get_missing()
```

```{r}
strings <- list(
  'Num_Acc' # keep for join
)
factors <- list(
  'hrmn', # to work - only keep hour - maybe group
  'lum',
  'dep',
  'agg', 
  'int', 
  'atm'
)
numericals <- list(
  'mois', # to consider seasons
  'lat',
  'long'
)
to_drop <- list(
  'adr', # too many mod
  'com', # too many mod
  'jour', # not relevant 
  'an' # only 1 mod
) 

caract <- set_data(caract, numericals, factors, strings)
caract <- caract %>% del_vars(to_drop)
```

```{r}
caract %>% head
caract %>% str
caract %>% summary
```

```{r}
write.csv2(caract, 'preprocessed_caract.csv')
```


## Lieux 

```{r}
lieux[lieux=="N/A"] <-  NA
lieux[lieux==-1] <-  NA
```

```{r}
lieux %>% head
lieux %>% str
```

```{r}
lieux %>% summary
```

```{r}
gg_miss_var(lieux)
vis_dat(lieux, warn_large_data=FALSE)
vis_miss(lieux, warn_large_data=FALSE)
get_missing(lieux)
```

```{r}
strings <- list(
  'Num_Acc' # keep for join
)
numericals <- list(

)
factors <- list(
  "catr",
  "circ",
  "nbv",
  "vosp",
  "prof",
  "plan",
  "surf", # regroup
  "infra",
  "situ",
  "vma")
to_drop <- list(
  "larrout", # 95% missing
  "lartpc", # 99% missing
  "voie", # irrelevant
  "pr", # irrelevant
  "pr1", #irrelevant
  "v1", # irrelevant
  "v2" # irrelevant
  )
```

```{r}
lieux <- set_data(lieux, numericals, factors, strings)
lieux <- lieux %>% del_vars(to_drop)
get_missing(lieux)
```

```{r}
lieux %>% head
lieux %>% str
lieux %>% summary
```

```{r}
write.csv2(lieux, 'preprocessed_lieux.csv')
```


## Véhicules

```{r}
vehicules <- read.csv2('../data/vehicules-2021.csv',
                    header=TRUE, 
                    sep=";")
```


```{r}
vehicules[vehicules=="N/A"] <-  NA
vehicules[vehicules==-1] <-  NA
```

```{r}
vehicules %>% head
vehicules %>% str
vehicules %>% summary
```

```{r}
vehicules %>% gg_miss_var()
vehicules %>% vis_dat(warn_large_data=FALSE)
vehicules %>% vis_miss(warn_large_data=FALSE)
vehicules %>% get_missing()
```

```{r}
vehicules$senc %>% table
vehicules$senc  %>% as.numeric %>% hist
```


```{r}
strings <- c(
  'Num_Acc', # note that a single accident can involve several vehicles
  'id_vehicule'
)
factors <- c(
  'senc',
  'catv',
  'obs',
  'obsm',
  'choc',
  'manv',
  'motor',
)
numericals <- c(
)
to_drop <- c(
  'num_veh', # irrelevant
  'occuct' # 99% missing
)
```

```{r}
vehicules <- set(vehicules, numericals, factors, strings)
vehicules <- vehicules %>% del_vars(to_drop)
vehicules %>% get_missing()
```

```{r}
vehicules %>% head
vehicules %>% str
vehicules %>% summary
```

## Usagers

```{r}
usagers <- read.csv2('../data/usagers-2021.csv',
                    header=TRUE, 
                    sep=";")
```

```{r}
usagers %>% head
usagers %>% str
usagers %>% summary
```

```{r}
usagers$actp %>% table
```


```{r}
usagers <- usagers %>% mutate_all(~ifelse(. == 'N/A', NA, .))
usagers <- usagers %>% mutate_all(~ifelse(. == '-1', NA, .))
usagers <- usagers %>% mutate_all(~ifelse(. == -1, NA, .))
```


```{r}
usagers %>% gg_miss_var()
usagers %>% vis_dat(warn_large_data=FALSE)
usagers %>% vis_miss(warn_large_data=FALSE)
usagers %>% get_missing()
```


```{r}
strings <- c(
  'Num_Acc',
  'id_vehicule'
)
factors <- c(
  'place',
  'catu',
  'grav',
  'sexe',
  'trajet',
  'secu1',
  'secu2',
  'locp',
  'actp'
)
numericals <- c(
  'an_nais'
)
to_drop <- c(
  'secu3', # too many NA, non NAs are note relevant (usagers$secu3 %>% table)
  'etatp',
  'num_veh'
) 
```

```{r}
usagers <- usagers %>% set_data(numericals, factors, strings)
usagers <- usagers %>% del_vars(to_drop)
usagers %>% get_missing()
```

```{r}
usagers %>% head
usagers %>% str
usagers %>% summary
```

## Target

```{r}
target_name <- 'grav' 
target <- usagers[,target_name]

data <- usagers
var <- target_name

g <- ggplot(data, aes(data[,var], colour=data[,var], fill=data[,var])) +
    geom_bar() +
    scale_color_discrete(name=var) + scale_fill_discrete(name=var)+
    labs(x=var)
print(g)

# g <- ggplot(data, aes(y=data[,target], x=data[,var], colour=data[,var], fill=data[,var])) +
#   geom_boxplot(alpha=0.5, outlier.alpha=0)+geom_jitter(width=0.25)+
#   stat_summary(fun=mean, colour="black", geom="point",shape=18, size=3)+
#   scale_color_discrete(name=var) + scale_fill_discrete(name=var)+
#   labs(x=var, y=target, title = paste(target, "vs", var))
# print(g)

# boxplot <- function(data, target, var)
```

## Data merger

```{r}
library(dplyr)
data <- caract %>% merge(vehicules, by='Num_Acc') %>% merge(usagers, by='Num_Acc') %>% merge(lieux, by='Num_Acc')
data %>% head

# data <- dplyr::reduce(list(caract, vehicules, usagers, lieux), full_join, by='Num_Acc')
# doesn't work
```

